import Footer from "./components/global/Footer";
import Header from "./components/global/Header";
import "./globals.css";
import { Instrument_Serif, Roboto } from "next/font/google";

const instrumentSerif = Instrument_Serif({
  subsets: ["normal"],
  weight: "400",
  variable: "--font-serif",
});
const roboto = Roboto({
  subsets: ["normal"],
  weight: "400",
  variable: "--font-sans",
});

export const metadata = {
  title: "Terpsicore",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`grid grid-cols-(--project-grid-cols) ${roboto.variable} ${instrumentSerif.variable} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
