import Footer from "./components/global/Footer";
import Header from "./components/global/Header";

import "./globals.css";
import { Instrument_Serif, Inter } from "next/font/google";

const instrumentSerif = Instrument_Serif({
  subsets: ["normal"],
  weight: "400",
  variable: "--font-serif",
});
const inter = Inter({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-sans",
});
export const metadata = {
  title: "Terpsicore",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`grid grid-cols-(--project-grid-cols) grid-rows-[auto_1fr_auto] ${inter.variable} ${instrumentSerif.variable} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
